#!/usr/bin/env bash
set -euo pipefail

export CUTE_DSL_ARCH="${CUTE_DSL_ARCH:-sm_121a}"
export SAFETENSORS_FAST_GPU="${SAFETENSORS_FAST_GPU:-1}"
export SGLANG_ENABLE_SPEC_V2="${SGLANG_ENABLE_SPEC_V2:-1}"
export SGLANG_PREVENT_THOUGHT_LOOPS="${SGLANG_PREVENT_THOUGHT_LOOPS:-1}"

exec "$@"
